# Generated by Django 3.2.6 on 2021-11-13 19:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('firstname', models.CharField(default='firstname', max_length=30)),
                ('lastname', models.CharField(default='lastname', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('empid', models.IntegerField(default=1234, primary_key=True, serialize=False)),
                ('ismanager', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Detail',
            fields=[
                ('teamname', models.CharField(default='Team 1', max_length=30)),
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Detail',
            fields=[
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organisation.employee')),
                ('Account_Id', models.CharField(blank=True, max_length=30, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=30, null=True)),
                ('Account_Name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organisation.employee')),
                ('attendance', models.IntegerField(default=0)),
                ('lastupdated', models.DateField(default=datetime.date(2001, 8, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.team_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Status', models.IntegerField(default=0)),
                ('Project_Description', models.TextField(default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.team_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(default='')),
                ('manager', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('date_applied', models.DateField()),
                ('date_from', models.DateField()),
                ('date_till', models.DateField()),
                ('reason', models.TextField(default='')),
                ('Status', models.IntegerField(default=0)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Chat_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Receiver', models.IntegerField(default=0)),
                ('Message', models.TextField(default='')),
                ('Sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organisation.employee')),
            ],
        ),
    ]
