# Generated by Django 3.2.6 on 2021-11-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='employee',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organisation.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organisation.employee'),
        ),
    ]
